// Generated by CoffeeScript 1.9.3
(function() {
  var animate, audio, noisePos, request, startViz, url;

  window.perlin = new ImprovedNoise();

  noisePos = Math.random() * 100;

  try {
    audio = new AudioContext();
  } catch (_error) {}

  url = 'data/11 Where I\'m Trying To Go (Marvel Years Remix).mp3';

  request = new XMLHttpRequest();

  request.open('GET', url, true);

  request.responseType = "arraybuffer";

  window.analyser = audio.createAnalyser();

  analyser.smoothingTimeConstant = 1;

  analyser.fftSize = 512;

  request.onload = function() {
    audio.decodeAudioData(request.response, function(buffer) {
      var source, sourceJs;
      source = audio.createBufferSource();
      source.buffer = buffer;
      source.connect(audio.destination);
      sourceJs = audio.createScriptProcessor(2048, 1, 1);
      sourceJs.buffer = buffer;
      source.connect(analyser);
      analyser.connect(sourceJs);
      sourceJs.onaudioprocess = function(e) {
        var array;
        array = new Uint8Array(analyser.frequencyBinCount);
        return analyser.getByteFrequencyData(array);
      };
      source.loop = true;
      startViz(source);
    });
  };

  startViz = function(source) {
    source.start(0);
    return animate();
  };

  animate = function() {
    requestAnimationFrame(animate);
    LoopVisualizer.update(noisePos);
    noisePos += 0.005;
    renderer.render(scene, camera);
  };

  request.send();

}).call(this);
